---
- hosts: all
  become: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
# command to run it : ansible-playbook apache.yml -i ./ansible-inventory.ini --ask-become-pass